version: '3.1'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
      POSTGRES_DB: local
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
