name: 機能追加
description: 機能追加
title: "[機能追加]: "
assignees:
  - eatski
body:
  - type: markdown
    attributes:
      value: |
        機能の追加について
  - type: textarea
    id: value
    attributes:
      label: どういった価値をもたらしたいか？何を解決したいか？
      placeholder: ログインなしでもクイズで遊べるようになる
    validations:
      required: true
  - type: textarea
    id: hindrance
    attributes:
      label: 何がこれを実現するのを妨げているか？（開発者の場合は入力）
      placeholder: bot等での不正利用
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: どうやって実現するか？（開発者の場合は入力）
    validations:
      required: false