name: Create PR from main to production

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          if [ $(gh pr list --head main --base production --json number --jq '. | length') -eq 0 ]; then
            gh pr create --title "Release to Production" --body "This PR is automatically created by the Github Actions" --head main --base production
          else
            echo "PR already exists between main and production."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
