name: Integration Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUPABASE_POSTGRES_URL_NON_POOLING: postgresql://postgres:@localhost:5432/postgres
      SUPABASE_POSTGRES_PRISMA_URL: postgresql://postgres:@localhost:5432/postgres?pgbouncer=true
      CI: 1
    services:
      postgres:
        image: postgres:13-alpine
        # refer: https://hub.docker.com/_/postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Prisma Migrate
        run: npx prisma migrate deploy
      
      - name: Prepare Test Data
        run: npm run test:prepare
      
      - name: Run Tests
        run: npm run test
      
        
